name: pinit
version: 0.1.0
github: "dotkuro/pinit"
license: AGPL-3
author: "Alexander Kampf"
maintainer: "akampftcg@gmail.com"
copyright: "2019 Alexander Kampf"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/dotKuro/pinit#readme>

dependencies:
  - base >= 4.7 && < 5
  - directory
  - dhall
  - filepath
  - text

library:
  source-dirs: src

executables:
  pinit:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pinit

tests:
  pinit-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pinit
